### ISSUE TITLE
IR LED not lighting up

### ISSUE THREAD

**Issue by primexa** [casper-gh/smartfan#3]
Hello,
I am having an issue with the IR LED. I have purchased the same IR kit that was depicted on your Smartthings community page https://community.smartthings.com/t/make-a-dumb-fan-smart-using-cheapo-esp8266-board-controllable-via-st-universal-ir-remote/47212
I have inputted the sendraw data to include the data I captured from the IRrecvDumpV2. The issue I have is that when the command is sent, the "Dat" light illuminates however, the IR LED does not come on. I have verified no illumination with Android phone camera. Is this something with the voltage and current from the board? How did you get your LED to light and transmit without any extra need for resistors or transistors? If the Data LED from the transmitter comes on, does this indicate the IR LED does not recognize the code structure? I would imagine Data LED lights, gives voltage to IR LED bulb, then the IR LED should light up. Any input would be greatly appreciated, thank you for your project and your time!

**Comment by casper-gh** [comment]
To make sure we're on the same page, you already have the IR code for your appliance and now trying to send the IR code from ESP8266? The "Dat" light you mentioned, is it the blue LED light on the IR module? If you got the same IR module as I have, when you fired a signal thru the IR LED, the blue light on the LED module should light up.

**Comment by primexa** [comment]
Thank you for getting back to me. Yes, I have the IR code (NEC for an LG TV) and just trying to send it. I did get the same IR module as you did. The DAT is the small yellow LED indicator that responds to a send signal which lights up perfectly, however the LED bulb does not. I have done some extensive troubleshooting and seems to be an issue with the code structure I using. I noticed this by uploading the sketch IRController.ino from mdhiggins. I was able to send the IR and lit up the LED bulb using this sketch. I am in the process of comparing what I did wrong with your sketch.

**Comment by casper-gh** [comment]
Either that's issue, or you just got a bad LED. Also, the LED indicator on my IR module is blue when it lights up. There's another issue with the LED module I have, that is the range is very short. So when you test it out, make sure you put the LED next to the device's IR receiver. Best of luck.
